#!/usr/bin/env bash

alias my-shell='ps -o command -p $$ | tail -n +2 | cut -d" " -f1 | sed "s/[^a-zA-Z]//"'
alias reload='rc=~/.`my-shell`rc; echo Loading $rc; source $rc'

# base ls command is OS dependent
if [[ $(uname) == "Linux" ]]; then
    alias ls='ls --color=auto'
else
    alias ls='ls -G'
fi
alias ll='ls -l'
alias la='ls -lA'
alias l='ls -CF'

alias v='nvim -u ~/.vimrc'
alias g='git'

alias cgrep='grep --color=always'
alias grep='grep --color=auto'
alias rm='rm -i'

alias pyclean='find . -name "*.pyc" -exec rm -f {} \;'
alias clean_build='rm -rf ../build/*'
alias my-scrot="scrot -s '%Y-%m-%dT%H:%M:%S.png' \
    -e 'mkdir -p ~/tmp/shots \&\& mv \$f ~/tmp/shots/'"

alias gitx='gitx -c'

alias ..='cd ..; ls'
alias rr='cd ~/Documents/research'
alias class='cd ~/Dropbox/Classes'
alias pc='pcui.py ~/Dropbox/var/pc.sqlite'
alias be='bundle exec'
alias now='date -u +"%Y-%m-%dT%H:%M:%SZ"'
alias now-epoch='date -u +%s'

calc(){ awk "BEGIN{ print $* }" ;}
dl() { mv -f "$*" ~/tmp/trash/; }

# database
alias pg-start='postgres -D /usr/local/var/postgres'

t() {
    bname=$(basename "${PWD/$HOME/~}")
    if [[ $# -lt 1 ]]; then
        echo -ne "\033]0;${USER}@${HOSTNAME}: ${bname}\007"
    else
        echo -ne "\033]0;$1\007"
    fi
}

pdfunlock() {
    gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile="$2" -c .setpdfwrite -f "$1"
}

conda-env() {
    source activate $(conda env list -v | tail +3 | awk '{ print $1 }' | fzf)
}
