#!/bin/bash

ENV_DIR=`pwd`
DST_DIR=${HOME}/tmp/env_test
OS=`uname`
LOCAL_EXT=".local"
SYMLINK_EXT=".symlink"

function op_if_does_not_exist() {
    local op=$1
    local msg=$2
    local src="${ENV_DIR}/$3"
    local dst="${DST_DIR}/$4"
    if [ -e $dst ]
    then
        local symbol="$(tput setaf 1)✗$(tput sgr0)"
    else
        $op "${src}" "${dst}"
        local symbol="$(tput setaf 2)✓$(tput sgr0)"
    fi
    echo "${symbol} ${msg}: $3"
}

function link_if_does_not_exist_src_dst() {
    op_if_does_not_exist "ln -sf" "Link" $1 $2
}

function link_hidden() {
    link_if_does_not_exist_src_dst "$1" ".$1"
}

function link() {
    link_if_does_not_exist_src_dst "$1" "$1"
}

function copy_if_does_not_exist_src_dst() {
    op_if_does_not_exist "cp -n" "Copy" $1 $2
}

function copy_hidden() {
    copy_if_does_not_exist_src_dst "$1" ".$1"
}

function setup_topic() {
    local topic=$1
    link_hidden $topic
    for rc in $(ls $topic/*$LOCAL_EXT 2> /dev/null)
    do
        topicrc=`basename ${rc%$LOCAL_EXT}`
        copy_if_does_not_exist_src_dst $rc .${topicrc}
    done
    for rc in $(ls $topic/*$SYMLINK_EXT 2> /dev/null)
    do
        topicrc=`basename ${rc%$SYMLINK_EXT}`
        link_if_does_not_exist_src_dst $rc .${topicrc}
    done

}

# setup topics
setup_topic bash
setup_topic shell
setup_topic tmux
setup_topic vim
setup_topic zsh
[ $OS == "Linux" ] && setup_topic i3



## application configurations
#link_hidden tmux.conf
#
## disabled applications
## synergy
## ln -sf ${ENV}/i3            ${HOME}/.i3
#
## bin
#mkdir ${DST_DIR}/bin
#for i in $(ls bin); do
#    link bin/$i
#done
