#!/bin/bash

ENV=`pwd`
OS=`uname`

function link_if_does_not_exist_src_dst() {
    local src="${ENV}/$1"
    local dst="${HOME}/$2"
    if [ -e $dst ]
    then
        echo "Not linking: $1"
    else
        echo "Linking: $1"
        ln -sf "${src}" "${dst}"
    fi
}

function link_hidden_if_does_not_exist() {
    link_if_does_not_exist_src_dst "$1" ".$1"
}

function link_if_does_not_exist() {
    link_if_does_not_exist_src_dst "$1" "$1"
}

# link to shell base
link_hidden_if_does_not_exist shell

# link to bash config files
link_hidden_if_does_not_exist bash
link_hidden_if_does_not_exist bash_profile
link_hidden_if_does_not_exist bashrc

# link to zsh config files
link_hidden_if_does_not_exist zsh

# link to vim files
link_hidden_if_does_not_exist vim
link_hidden_if_does_not_exist gvimrc
cp -n  ${ENV}/vimrc ${HOME}/.vimrc || echo "vimrc exists not overwriting"

# application configurations
link_hidden_if_does_not_exist tmux.conf

# disabled applications
# synergy
# ln -sf ${ENV}/i3            ${HOME}/.i3
