#!/usr/bin/env bash

# by default, the i3-msg command makes requests to the i3 socket at $I3SOCK.
# Sometimes, this variable is not updated with i3 restarts (e.g. when using
# tmux) and so it can become stale. In this script, when we invoking i3-msg, we
# use the -s flag to specify the socket to use so that we can be sure we are
# talking to the socket for the current i3 instance
# This function is just a wrapper around i3-msg that will always use the current
# socket
function i3msg() {
    i3-msg -s $(i3 --get-socket) $@
}

function activateWorkspace() {
    number=$1

    i3msg workspace number $number
}

function moveActiveWorkspaceToOuput() {
    output=$1

    i3msg move workspace to output $output
}

function restartI3() {
    i3msg restart -s $(i3 --get-socket)
}

function moveWorkspaceToOutput() {
    number=$1
    output=$2

    activateWorkspace $number
    moveActiveWorkspaceToOuput $output
}

function setOutputsForHomeOffice() {
    xrandr \
        --output eDP-1 --primary --mode 1920x1080 --pos 0x360 --rotate normal \
        --output DP-1 --mode 2560x1440 --pos 1920x0 --rotate normal \
        --output HDMI-1 --off \
        --output DP-2 --off
}

function setWorkspacesForHomeOffice() {
    left="xinerama-0"
    center="xinerama-1"

    moveWorkspaceToOutput 1 $center
    moveWorkspaceToOutput 2 $center
    moveWorkspaceToOutput 3 $center
    moveWorkspaceToOutput 4 $center
    moveWorkspaceToOutput 5 $center
    moveWorkspaceToOutput 6 $center
    moveWorkspaceToOutput 7 $center
    moveWorkspaceToOutput 8 $center
    moveWorkspaceToOutput 9 $center
    moveWorkspaceToOutput 0 $left

    activateWorkspace 0
    activateWorkspace 4
}


function setOutputsForMobileOffice() {
    xrandr \
        --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
        --output DP-1 --off \
        --output HDMI-1 --off \
        --output DP-2 --mode 1920x1080 --pos 1920x0 --rotate normal
}

function setWorkspacesForMobileOffice() {
    center="xinerama-0"
    right="xinerama-1"

    moveWorkspaceToOutput 1 $center
    moveWorkspaceToOutput 2 $center
    moveWorkspaceToOutput 3 $center
    moveWorkspaceToOutput 4 $center
    moveWorkspaceToOutput 5 $center
    moveWorkspaceToOutput 6 $right
    moveWorkspaceToOutput 7 $right
    moveWorkspaceToOutput 8 $right
    moveWorkspaceToOutput 9 $right
    moveWorkspaceToOutput 0 $right

    activateWorkspace 3
    activateWorkspace 7

    activateWorkspace 3
}

function setOutputsForCoffeeShop() {
    xrandr \
        --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
        --output DP-1 --off \
        --output HDMI-1 --off \
        --output DP-2 --off
}

function setWorkspacesForCoffeeShop() {
    center="xinerama-0"

    moveWorkspaceToOutput 1 $center
    moveWorkspaceToOutput 2 $center
    moveWorkspaceToOutput 3 $center
    moveWorkspaceToOutput 4 $center
    moveWorkspaceToOutput 5 $center
    moveWorkspaceToOutput 6 $center
    moveWorkspaceToOutput 7 $center
    moveWorkspaceToOutput 8 $center
    moveWorkspaceToOutput 9 $center
    moveWorkspaceToOutput 0 $center

    activateWorkspace 1
}

function setupForCoffeeShop() {
    setOutputsForCoffeeShop
    restartI3
    setWorkspacesForCoffeeShop
}

function setupForHomeOffice() {
    setOutputsForHomeOffice
    restartI3
    setWorkspacesForHomeOffice
}


config=$1
case $config in
    coffee-outputs)
        setOutputsForCoffeeShop
        ;;
    coffee-workspaces)
        setWorkspacesForCoffeeShop
        ;;
    mobile-outputs)
        setOutputsForMobileOffice
        ;;
    mobile-workspaces)
        setWorkspacesForMobileOffice
        ;;
    home-outputs)
        setOutputsForHomeOffice
        ;;
    home-workspaces)
        setWorkspacesForHomeOffice
        ;;
    help)
        {
            echo "Useage: $0 <config>"
            echo ""
            echo "valid config values are:"
            echo "  - coffee-outputs"
            echo "  - coffee-workspaces"
            echo "  - mobile-outputs"
            echo "  - mobile-workspaces"
            echo "  - home-outputs"
            echo "  - home-workspaces"
        } >&2
        exit 1
        ;;
    *)
        $0 $($0 help 2>&1 | tail +4 | fzf | sed -e 's/-//')
        ;;
esac
