#!/usr/bin/env bash

# base ls command is OS dependent
if [[ $(uname) == "Linux" ]]; then
    alias ls='ls --color=auto'
else
    alias ls='ls -G'
fi

alias g='git'
alias l='ls -CF'
alias la='ls -lA'
alias ll='ls -l'

alias j='journal edit'
alias t='tmux-sessionizer'
alias v='nvim'

alias grep='grep --color=auto'
alias rm='rm -i'

alias ..='cd ..; ls'
alias now='date -u +"%Y-%m-%dT%H:%M:%SZ"'
alias today='date -u +"%Y-%m-%d"'

alias reload='echo $SHELL | xargs basename | xargs -I {} echo source ~/.{}rc'

project() {
    local awkScript="{ print \$$1"
    for var in "${@:2}"; do
        awkScript="${awkScript}, \$$var"
    done
    awkScript="${awkScript} }"
    awk $awkScript
}

