source ~/.zplug/init.zsh
# do not auto load virtual environments
# export DISABLE_VENV_CD=1

zplug "b4b4r07/zplug"
# zplug "mafredri/zsh-async"
# zplug "sindresorhus/pure", on:"mafredri/zsh-async"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "zdharma/fast-syntax-highlighting", defer:2
zplug "Tarrasch/zsh-colors"
zplug "ohmyzsh/oh-my-zsh", use:"lib/history.zsh"
zplug "ohmyzsh/oh-my-zsh", use:"lib/directories.zsh"
# zplug "jeffreytse/zsh-vi-mode"

# use default readline keybindings
bindkey -e

# do not update the title in every command
export DISABLE_AUTO_TITLE="true";

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load

# some of my favorite options
setopt autocd

# shared between bash and zsh
source ${HOME}/.shell/shared

# complete .. to ../
zstyle ':completion:*' special-dirs true

# Add local bin path
export PATH="$HOME/bin/scripts/:$HOME/bin/scripts-bky/:$HOME/bin:$HOME/.local/bin:$PATH"

# set the word characters, the stuff in the [] is removed from the
# word char definition.  Specifically, deleting / allows for
# removing parts of paths with C-w
export WORDCHARS=${WORDCHARS//[\/]}
