source ~/.zplug/init.zsh

zplug "b4b4r07/zplug"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "zdharma/fast-syntax-highlighting", defer:2
zplug "Tarrasch/zsh-colors"
zplug "ohmyzsh/oh-my-zsh", use:"lib/history.zsh"
zplug "ohmyzsh/oh-my-zsh", use:"lib/directories.zsh"

# use default readline keybindings
bindkey -e

# do not update the title in every command
export DISABLE_AUTO_TITLE="true";

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load

# some of my favorite options
setopt autocd

# source additional files
source $HOME/.config/zsh/aliases
source $HOME/.config/zsh/env_vars

# complete .. to ../
zstyle ':completion:*' special-dirs true

# Add local bin path
export PATH="$HOME/bin/scripts/:$PATH"
export PATH="$HOME/bin/scripts-bky/:$PATH"
export PATH="$HOME/bin:$PATH"

# set the word characters, the stuff in the [] is removed from the
# word char definition.  Specifically, deleting / allows for
# removing parts of paths with C-w
export WORDCHARS=${WORDCHARS//[\/]}

# setup shell tools
# make sure to run atin after fzf so that ctrl-r
# is handled by atuin
eval "$(direnv hook zsh)"
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(fzf --zsh)"
eval "$(atuin init zsh --disable-up-arrow)"

# use ripgrep FZF
export FZF_DEFAULT_COMMAND="rg --hidden --glob '!**/.git/**' --files"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
