source ~/.zplug/init.zsh

# do not auto load virtual environments
export DISABLE_VENV_CD=1

zplug "b4b4r07/zplug"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "mafredri/zsh-async"
zplug "sindresorhus/pure", on:"mafredri/zsh-async"
zplug "zsh-users/zsh-completions"
zplug "plugins/virtualenvwrapper", from:oh-my-zsh
zplug "plugins/vi-mode", from:oh-my-zsh
zplug "djui/alias-tips"
zplug "Tarrasch/zsh-colors"
zplug "caarlos0/zsh-pg"
zplug "robbyrussell/oh-my-zsh", use:"lib/history.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/directories.zsh"

# do not update the title in every command
export DISABLE_AUTO_TITLE="true";

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load

# some of my favorite options
setopt autocd

# load zle
source ${HOME}/.zsh/zle.zsh

# shared between bash and zsh
source ${HOME}/.shell/shared

# complete .. to ../
zstyle ':completion:*' special-dirs true

# Add local bin path
export PATH="$PATH:$HOME/bin"
